[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"

[environments.production]
STREAMLIT_SERVER_PORT = "$PORT"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_FILE_WATCHER_TYPE = "none"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
MODEL_NAME = "TestModel"
